In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

# Подключение
engine = create_engine('postgresql://dmitriy:password@localhost:5432/shop')

# Получить список всех таблиц
query = """
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public'
ORDER BY table_name;
"""

df_tables = pd.read_sql(query, engine)
print("Список таблиц в базе данных 'shop':")
df_tables

Список таблиц в базе данных 'shop':

    table_name
0    customers
1  order_items
2       orders
3     products

In [2]:
# 1. Таблица пользователи
df_customers = pd.read_sql("SELECT * FROM customers;", engine)
df_customers.head(5)

   id                        name             city registered_at
0   0     Шубин Иван Феоктистович      д. Челюскин    2025-04-01
1   1       Фокин Артем Давыдович        с. Ковров    2025-08-11
2   2      Евсеев Фадей Ефремович  с. Горячий Ключ    2026-03-08
3   3  Марфа Станиславовна Носова        ст. Анапа    2025-03-24
4   4  Авдеев Виссарион Фёдорович         д. Асино    2025-04-15

In [3]:
# 2. Таблица products
df_products = pd.read_sql("SELECT * FROM products;", engine)
df_products.head(5)

   id                                          name category  price
0   0                    27" Монитор MSI PRO MP273A  Монитор  10599
1   1                      27" Монитор Xiaomi G27Qi  Монитор  18599
2   2  27" Монитор ARDOR GAMING INFINITY PRO AQ27H1  Монитор  17299
3   3                     27" Монитор MSI MAG 275QF  Монитор  14699
4   4                     23.8" Монитор Xiaomi A24i  Монитор   8099

In [4]:
# 3. Таблица orders
df_orders = pd.read_sql("SELECT * FROM orders;", engine)
df_orders.head(5)

   id  customer_id  order_date      status
0   0           66  2025-11-14   completed
1   1           98  2026-02-07   cancelled
2   2           61  2025-09-26   cancelled
3   3           87  2025-11-26  processing
4   4           96  2025-09-11  processing

In [5]:
# 4. Таблица order_items
df_order_items = pd.read_sql("SELECT * FROM order_items;", engine)
df_order_items.head(5)

   order_id  product_id  quantity
0         0           4         3
1         0          37         3
2         1          14         2
3         1          12         1
4         1          29         3

In [6]:
df = pd.read_sql("SELECT min(order_date), max(order_date) FROM orders;", engine)
df

          min         max
0  2025-04-20  2026-04-20